### ISSUE TITLE
not enough arguments in call to syscall.Syscall

### ISSUE THREAD

**Issue by cage1016** [mconintet/progressbar#1]
$ export GOOS=windows

$ go build -o data.exe data.go
# github.com/mconintet/progressbar

../github.com/mconintet/progressbar/progressbar.go:22: undefined: syscall.SYS_IOCTL
../github.com/mconintet/progressbar/progressbar.go:24: undefined: syscall.TIOCGWINSZ
../github.com/mconintet/progressbar/progressbar.go:26: not enough arguments in call to syscall.Syscall

**Comment by mconintet** [comment]
it does not support windows command line :-p
